config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root to: 'posts#index'

  resources :posts
  devise_for :users
  resources :likes, only: [:create, :destroy]
  get 'about', to: 'application#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
# == Schema Information
#
# Table name: likes
#
#  id         :bigint           not null, primary key
#  user_id    :bigint           not null
#  post_id    :bigint           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :post, uniqueness: { scope: :user }
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint           not null, primary key
#  title      :string           not null
#  body       :text             not null
#  author_id  :bigint           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Post < ApplicationRecord
  include ActionView::Helpers::DateHelper

  validates :title, :body, presence: true

  belongs_to :author,
    class_name: :User

  has_many :likes,
    dependent: :destroy

  has_many :user_likes,
    through: :likes,
    source: :user

  def history
    history = 
      if created_at > 4.days.ago
        time_ago_in_words(created_at) + ' ago'
      else
        created_at.strftime('%b %-d %Y')
      end
    created_at == updated_at ? history : (history + '<i> (edited)</i>').html_safe
  end
end

app/models/posts.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint           not null, primary key
#  title      :string           not null
#  body       :text             not null
#  author_id  :bigint           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Post < ApplicationRecord
    include ActionView::Helpers::DateHelper
  
    validates :title, :body, presence: true
  
    belongs_to :author,
      class_name: :User
  
    has_many :likes,
      dependent: :destroy
  
    has_many :user_likes,
      through: :likes,
      source: :user
  
    def history
      history = 
        if created_at > 4.days.ago
          time_ago_in_words(created_at) + ' ago'
        else
          created_at.strftime('%b %-d %Y')
        end
      created_at == updated_at ? history : (history + '<i> (edited)</i>').html_safe
    end
  end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  username               :string           not null
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, uniqueness: true

  has_many :posts,
    foreign_key: :author_id,
    dependent: :destroy

  has_many :likes,
    dependent: :destroy

  has_many :liked_posts,
    through: :likes,
    source: :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def about
    render 'shared/about'
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    if params[:like][:user_id].to_i == current_user.id
      Like.create(like_params)
    else
      # do nothing
    end
    redirect_back fallback_location: root_url
  end

  def destroy
    like = Like.find(params[:id])
    if like.user == current_user
      Like.destroy(params[:id])
    else
      # do nothing
    end
    redirect_back fallback_location: root_url
  end

  private

  def like_params
    params.require(:like).permit(:user_id, :post_id)
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :require_author!, only: [:edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order(created_at: :desc)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.author = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end

    def require_author!
      unless current_user.try(:id) == @post.author_id
        flash[:alert] = 'You are not authorized to edit this post!'
        redirect_to root_url
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/07b0558508.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <header>
      <div class='header-left'>
        <button class='header-button border-right'>
          <%= link_to 'Home', root_path, class: 'header-item' %>
        </button><!--
        --><button class='header-button'>
          <%= link_to 'About', about_path, class: 'header-item' %>
        </button>
      </div>
      <div class='header-right'>
        <button class='header-button border-right'>
          <%= link_to 'New Post', new_post_path, class: 'header-item' %>
        </button><!--
        <% if user_signed_in? %>
          --><button class='header-button border-right'>
            <%= link_to current_user.username, edit_user_registration_path, class: 'header-item' %>
          </button><!--
          --><button class='header-button'>
            <%= link_to 'Logout', destroy_user_session_path, class: 'header-item', method: :delete %>
          </button>
        <% else %>
          --><button class='header-button border-right'>
            <%= link_to 'Login', new_user_session_path, class: 'header-item' %>
          </button><!--
          --><button class='header-button'>
            <%= link_to 'Sign Up', new_user_registration_path, class: 'header-item' %>
          </button>
        <% end %>
      </div>
    </header>
    <p id="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, rows: '20', cols: '80' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'important-button' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class='page-body'>
  <h1>Edit Post</h1>

  <%= render 'form', post: @post %>

  <%= link_to 'Show', @post %> |
  <%= link_to 'Back', posts_path %>
</div>

app/views/posts/index.html.erb
<div class='posts'>
  <% @posts.includes(:likes, :author).each do |post| %>
    <div class='post'>  
      <div class='title'><%= post.title %></div>
      <div class='history'><%= post.history %></div>
      <div class='body'><%= post.body %></div>
      <div class='like-count'><i class="fas fa-thumbs-up"></i><%= post.likes.length %></div>
      <% if user_signed_in? %>
        <div class='like'>
          <% like = post.likes.find { |like| like.user_id == current_user.id } %>
          <% if like %>
            <%= button_to 'Unlike', like_path(like), method: :delete, class: 'like-link'%>
          <% else %>
            <%= button_to 'Like', likes_path, params: { like: { user_id: current_user, post_id: post } }, class: 'like-link' %>
          <% end %>
        </div>
        <div class='author'><%= post.author.username %></div>
      <% else %>
        <div class='like-border'></div>
      <% end %>
      <div class='post-links'>
        <%= link_to 'Show', post %>
        <% if current_user.try(:id) == post.author_id %>
          <%= link_to 'Edit', edit_post_path(post) %>
          <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </div>
    </div>
    <br>
  <% end %>
</div>

app/views/posts/index0.html.erb
<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Likes</th>
      <% if user_signed_in? %>
        <th></th>
        <th>Author</th>
      <% end %>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.includes(:likes, :author).each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= post.likes.length %>
        <% if user_signed_in? %>
          <% like = post.likes.find { |like| like.user_id == current_user.id } %>
          <%# like = Like.find_by(user: current_user, post: post) %>
          <!-- I know using SQL for this kind of task is generally preferable, especially since Ruby isn't
               able to make use of the database index on user_id in the likes table. However, this does
               eliminate an n+1 query situation. I didn't know how to eager load the specific like that
               meets the criteria I need while still eager loading the other required data. With a small
               amount of data, the Ruby approach is notably faster. -->
          <% if like %>
            <td><%= button_to 'Unlike', like_path(like), method: :delete %></td>
          <% else %>
            <td><%= button_to 'Like', likes_path, params: { like: { user_id: current_user, post_id: post } } %></td>
          <% end %>
          <td><%= post.author.username %></td>
        <% end %>
        <td><%= link_to 'Show', post %></td>
        <% if current_user.try(:id) == post.author_id %>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
          <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<div class='page-body'>
  <h1>New Post</h1>

  <%= render 'form', post: @post %>

  <%= link_to 'Back', posts_path %>
</div>

app/views/posts/show.html.erb
<div class='page-body'>
  <p>
    <strong>Title:</strong>
    <%= @post.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= @post.body %>
  </p>

  <p>
    <strong>Likes:</strong>
    <%= @post.likes.count %>
  </p>

  <% if user_signed_in? %>
    <p>
      <strong>Author:</strong>
      <%= @post.author.username %>
    </p>
    <p>
      <strong>Liked by:</strong>
      <ul>
        <% @post.user_likes.each do |user| %>
          <li><%= user.username %></li>
        <% end %>
      </ul>
    </p>
    <% like = Like.find_by(user: current_user, post: @post) %>
    <% if like %>
      <%= button_to 'Unlike', like_path(like), method: :delete, class: 'like-link'%>
    <% else %>
      <%= button_to 'Like', likes_path, params: { like: { user_id: current_user, post_id: @post } }, class: 'like-link' %>
    <% end %>
  <% end %>

  <br>
  <%= link_to 'Back', posts_path %>
  <% if current_user.try(:id) == @post.author_id %>
    <%= link_to 'Edit', edit_post_path(@post) %>
    <%= link_to 'Delete', @post, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
</div>

app/views/shared/about.html.erb
<div class='page-body'>
  <p>Microverse Coutersy<%=
    link_to 'curriculum', 'https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication'
    %>. View on <%=
    link_to 'Github', 'https://github.com/' %>.</p>
  <p>For full functionality sign up or login with <i>odin@example.com</i> and <i>password</i>.</p>
</div>